language: julia

os:
  - linux
  - osx

julia:
#  - 1.0
  - 1.3
#  - nightly

# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
#matrix:
#   allow_failures:
#   - julia: 1.3
#   - julia: nightly

notifications:
  email: false

install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py --user
  - pip3 install --user matplotlib
  - pip3 install --user jupyter

script: # the default script is equivalent to the following
  - echo $PATH
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --eval 'using Pkg; Pkg.instantiate();'
  - julia --project --eval 'using Pkg; Pkg.status();'
  - julia --project --eval 'using Pkg; Pkg.add(PackageSpec(name="DIVAnd", rev="master"));'
  - jupyter kernelspec list
  - utils/test-notebooks
